### ISSUE TITLE
Encountered issues when creating your user from the chainlink onboard email

### ISSUE THREAD

**Issue by charifmews** [SxT-Community/python-api-examples#1]
First the `AUTH_SCHEME = "ED25519"` in the sample.env default is set wrong for the API, because it doesn't recognise the scheme. Only when you set it to lowercase letters ('ed25519') the API accepts it.

Second the `API_URL` from the chainlink mail is missing a trailing slash and the versioning part of the API URL. Would suggest the scripts checks for a trailing slash and versioning, if missing just format it like `<SxT-API-URL-HERE>/v1/` or maybe send a follow-up email. 

Thirdly I could not generate the keys properly with generate-keys.py so that the API would accept it (I'm using a new macbook pro with python 3.11). This script + dependency works for me:

```sh
pip install cryptography
```

```python
import os
import base64
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

# Generate a random 32-byte seed
seed = os.urandom(32)

# Create a private key from the seed
private_key = Ed25519PrivateKey.from_private_bytes(seed)

# Get the corresponding public key
public_key = private_key.public_key()

# Encode the private and public keys as bytes
private_key_bytes = private_key.private_bytes(
    encoding=serialization.Encoding.Raw,
    format=serialization.PrivateFormat.Raw,
    encryption_algorithm=serialization.NoEncryption()
)
public_key_bytes = public_key.public_bytes(
    encoding=serialization.Encoding.Raw,
    format=serialization.PublicFormat.Raw
)

# Encode the private key, and public key in Base64 format
private_key_base64 = base64.b64encode(private_key_bytes)
public_key_base64 = base64.b64encode(public_key_bytes)

# Print the private key, and public key in Base64 format
print("Private Key (Base64):", private_key_base64.decode())
print("Public Key (Base64):", public_key_base64.decode())
```

**Comment by chilaraiSxt** [comment]
Thanks for reporting. Taking a look at it

**Comment by nopslip** [comment]
+1. Thanks @charifmews 

1) I've updated the sample.env to reference the newly case-sensitive requirements of the gateway (ed25529 instead of ED25529)
2) I updated sample.env to show that `/v1/` is needed. For now, this will be better than something at the code level, as the API URL format may change closer to the production release. 
3) I've broken the keygen scripts into two separate scripts and used your code with the cryptography package to generate the [Ed25519 keys](https://github.com/SxT-Community/python-api-examples/blob/main/generate-Ed25519-keys.py). I tested key generation and registration successfully. 

I still need to update the notebook branch with the new keygen code and .env updates.
